### ISSUE TITLE
19:57:37 [WARN] RakNetServer: Handled exception java.lang.IndexOutOfBoundsException caused by address /49.207.54.145:25243

### ISSUE THREAD

**Issue by diclofoss** [JRakNet/JRakNet#108] opened 2019-05-27 17:02 UTC
Version 2.10.7
Exception received when UNRELIABLE_SEQUENCED mode

**Comment by whirvis** [comment] 2019-05-27 17:44
I will need to see the actual exception stack trace, along with the code you were using when this occurred. Typically, when you get a message saying that an exception was caused by another address, that means an exception occurred when handling a packet that was sent by another address. This is sometimes due to faulty code on the part of the server, however it is assumed that the client sent an invalid or malicious packet so as to prevent crashes on the side of the server.

**Comment by diclofoss** [comment] 2019-05-27 18:10
You are not printing stacktrace

**Comment by whirvis** [comment] 2019-05-28 15:50
There is a method called onHandlerException() in RakNetServerListener, override that and take the throwable and print its stack trace if possible :)

**Comment by diclofoss** [comment] 2019-06-04 08:18
I think we need to check new version. I found issue on my side for this

**Comment by whirvis** [comment] 2019-06-04 13:24
Alright, let me know if the issue is fixed in the new version :)

**Closed as completed** 2019-06-06 21:52 UTC
Labels: Possible bug, v2.0
