### ISSUE TITLE
sendMessage(Reliability.UNRELIABLE_SEQUENCED, packet); not working at all

### ISSUE THREAD

**Issue by diclofoss** [JRakNet/JRakNet#109] opened 2019-05-28 09:51 UTC
When I set sendMessage(Reliability.UNRELIABLE_SEQUENCED, packet); packets are not sent at all
When I set peer.sendMessage(Reliability.RELIABLE_ORDERED, packet); works fine

**Comment by whirvis** [comment] 2019-05-28 15:51
Could I see the code you are using?

**Comment by diclofoss** [comment] 2019-05-28 19:06
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.samp_net.voiceserver2;

import com.whirvis.jraknet.RakNetPacket;
import com.whirvis.jraknet.peer.RakNetClientPeer;
import com.whirvis.jraknet.protocol.Reliability;
import java.util.ArrayList;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.samp_net.imdb.ImdbManager;
import ru.samp_net.imdb.ImdbPlayerLocation;

/**
 *
 * @author Khlupin
 */
public class Player {

    private final static List<Player> playerList = new ArrayList<>();
    private static final Logger logger = LoggerFactory.getLogger(Player .class);

    public static synchronized void register(int playerid, RakNetClientPeer peer) {
        Player player = get(playerid);
        if (player != null) {
            player.peer = peer;
            return;
        }
        playerList.add(new Player(peer, playerid));
    }

    public static synchronized void disconnect(RakNetClientPeer peer) {
        Player player = get(peer);
        if (player != null) {
            playerList.remove(player);
        }
    }

    public static synchronized Player get(int playerid) {
        for (Player player : playerList) {
            if (player.playerid == playerid) {
                return player;
            }
        }
        return null;
    }

    static synchronized Player get(RakNetClientPeer peer) {
        for (Player player : playerList) {
            if (player.peer.getGloballyUniqueId() == peer.getGloballyUniqueId()) {
                return player;
            }
        }
        return null;
    }

    static void sendData(ImdbManager imdbManager, int playerid, RakNetPacket packet) {
        List<ImdbPlayerLocation> imdbPlayerLocationList = imdbManager.getLocationList(playerid, 30.0f);
        for (ImdbPlayerLocation imdbPlayerLocation : imdbPlayerLocationList) {
            Player player = Player.get(imdbPlayerLocation.getPlayerid());
            if (player == null) {
                continue;
            }
            player.send(packet);
        }
    }

    RakNetClientPeer peer;
    int playerid;

    public Player(RakNetClientPeer peer, int playerid) {
        this.peer = peer;
        this.playerid = playerid;
    }

    private void send(RakNetPacket packet) {
        logger.info("send voice");
        peer.sendMessage(Reliability.UNRELIABLE_SEQUENCED, packet);
    }

}

**Comment by diclofoss** [comment] 2019-05-28 19:06
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.samp_net.voiceserver2;

import com.whirvis.jraknet.InvalidChannelException;
import com.whirvis.jraknet.Packet;
import com.whirvis.jraknet.RakNetException;
import com.whirvis.jraknet.RakNetPacket;
import com.whirvis.jraknet.identifier.Identifier;
import com.whirvis.jraknet.peer.RakNetClientPeer;
import com.whirvis.jraknet.protocol.ConnectionType;
import com.whirvis.jraknet.protocol.Reliability;
import com.whirvis.jraknet.server.RakNetServer;
import com.whirvis.jraknet.server.RakNetServerListener;
import java.net.InetSocketAddress;
import java.util.List;
import org.apache.commons.lang3.exception.ExceptionUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.samp_net.imdb.ImdbManager;
import ru.samp_net.imdb.ImdbPlayerLocation;

/**
 *
 * @author Khlupin
 */
public class VoiceServer2 {

    private static final Logger logger = LoggerFactory.getLogger(VoiceServer2.class);

    public static void main(String args[]) throws RakNetException {

        // Create server
        RakNetServer server = new RakNetServer(6999, 999, new Identifier("Samp-net Voice server"));
        ImdbManager imdbManager = new ImdbManager();
        logger.info("Protocol Version: " + server.getProtocolVersion());
        // Add listener
        server.addListener(new RakNetServerListener() {
            @Override
            public void onConnect(RakNetServer server, InetSocketAddress address, ConnectionType connectionType) {
                RakNetServerListener.super.onConnect(server, address, connectionType); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void onLogin(RakNetServer server, RakNetClientPeer peer) {
                logger.info("Client from address " + peer.getAddress() + " has connected to the server");
            }

            @Override
            public void onDisconnect(RakNetServer server, InetSocketAddress address, RakNetClientPeer peer, String reason) {
                Player.disconnect(peer);
                logger.info("Player has been disconnected");
            }

            @Override
            public void handleMessage(RakNetServer server, RakNetClientPeer peer, RakNetPacket packet, int channel) {
                try {
                    int code = packet.readInt();
                    logger.info("New packet with code: " + code + " and packetId = " + packet.getId());
                    switch (code) {
                        case 20: {
                            int playerid = packet.readInt();
                            Player.register(playerid, peer);
                            Packet destPacket = new Packet();
                            destPacket.writeByte(135);
                            destPacket.writeInt(0);
                            peer.sendMessage(Reliability.RELIABLE_ORDERED, destPacket);
                            logger.info("New connection player with id: " + playerid);
                            break;
                        }
                        case 21: {
                            Player player = Player.get(peer);
                            if (player == null) {
                                logger.warn("Player not found on sending voice data");
                                break;
                            }
                            List<ImdbPlayerLocation> locationList = imdbManager.getLocationList(player.playerid, 30.0f);
                            logger.info("Locations list size: " + locationList.size());
                            for (ImdbPlayerLocation imdbPlayerLocation : locationList) {
                                Player.sendData(imdbManager, imdbPlayerLocation.getPlayerid(), packet);
                            }
                            break;
                        }
                        default:
                            logger.warn("Unknown code: " + code);
                    }
                    logger.info("Client from address " + peer.getAddress() + " sent packet with ID "
                            + packet.getId() + " on channel " + channel + " with code: " + code);

                } catch (InvalidChannelException ex) {
                    logger.error(ex.getMessage());
                    logger.error(ExceptionUtils.getStackTrace(ex));
                }
            }

        });

// Start server
        server.start();
    }

}

**Comment by diclofoss** [comment] 2019-05-28 19:18
This is a part from game:

			RakNet::BitStream bsOut;
			bsOut.Write((RakNet::MessageID)ID_GAME_MESSAGE_1);
			bsOut.Write(21);
			bsOut.Write(VoiceClient::playerid);
			bsOut.Write(packetWithVoice.size);
			bsOut.Write(packetWithVoice.data, packetWithVoice.size);
			VoiceClient::peer->Send(&bsOut, HIGH_PRIORITY, UNRELIABLE_SEQUENCED, 0, VoiceClient::systemAddress, false);

**Comment by whirvis** [comment] 2019-05-28 23:03
When you say it does not work at all, do you mean the packet is never received? Also, have you tried sending on different reliabilities? If possible, try sending on different reliabilities. Also, I notice you are using something called a ``VoiceClient``, which I believe is built into RakNet. JRakNet does not support this by default. When RakNet packets are sent and are unimplemented by JRakNet, they are sent down to the ``handleUnknownMessage()`` method in the ``RakNetServerListener``. I believe the packet is being received, but just not handled and sent to that method. If nothing shows up in that ``handleUnknownMessage()`` method, try sending a different packet with an ID greater than 0x86 with the UNRELIABLE_SEQUENCED reliability.

**Comment by diclofoss** [comment] 2019-05-29 13:17
Ok I have added onHandlerException

My code on C++ RakNet: 

RakNet::BitStream bsOut;
bsOut.Write((RakNet::MessageID)ID_GAME_MESSAGE_1);
bsOut.Write((byte)1);
peer->Send(&bsOut, HIGH_PRIORITY, UNRELIABLE_SEQUENCED, 0, packet->systemAddress, false);

Exception on server:
18:45:40 [ERROR] VoiceServer: readerIndex(131) + length(1) exceeds writerIndex(131): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 131, widx: 131, cap: 131)
18:45:40 [ERROR] VoiceServer: java.lang.IndexOutOfBoundsException: readerIndex(131) + length(1) exceeds writerIndex(131): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 131, widx: 131, cap: 131)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707)
	at com.whirvis.jraknet.Packet.read(Packet.java:155)
	at com.whirvis.jraknet.protocol.message.EncapsulatedPacket.decode(EncapsulatedPacket.java:162)
	at com.whirvis.jraknet.protocol.message.CustomPacket.decode(CustomPacket.java:118)
	at com.whirvis.jraknet.server.RakNetServer.handleMessage(RakNetServer.java:677)
	at com.whirvis.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:144)

**Comment by diclofoss** [comment] 2019-05-29 13:18
bsOut.Write((RakNet::MessageID)ID_GAME_MESSAGE_1); see as (byte)135

**Comment by whirvis** [comment] 2019-05-29 16:22
1. Did you do of what I asked, and send on another reliability?
2. Did you try the handleUnknownMessage() function, to make sure that the server is actually getting nothing and not simply ignoring a RakNet packet it has not implemented?
3. Did you try sending another packet with an ID greater than 0x86 with the UNRELIABLE_SEQUENCED reliability?

Please answer these questions. Also you must **always** send Java code with stack traces, it makes it impossible to discover the cause otherwise.

**Comment by diclofoss** [comment] 2019-05-29 17:08
1 - yes it works
2 - Yes I did, exception is during the parsing packet on your level. 
3 - Yes The packet id is: 135

This is pure your stacktrace and error before my code

Anyway here is my code:

public class VoiceServer {

    private static final Logger logger = LoggerFactory.getLogger(VoiceServer.class);

    public static void main(String args[]) throws RakNetException {

        // Create server
        RakNetServer server = new RakNetServer(6999, 999, new Identifier("Samp-net Voice server"));
        ImdbManager imdbManager = new ImdbManager();
        logger.info("Protocol Version: " + server.getProtocolVersion());
        // Add listener
        server.addListener(new RakNetServerListener() {
            @Override
            public void onClientConnect(RakNetClientSession peer) {
                logger.info("Client from address " + peer.getAddress() + " has connected to the server");
            }

            @Override
            public void onClientDisconnect(RakNetClientSession session, String reason) {
                logger.info("Player has been disconnected");
            }

            @Override
            public void onSessionException(RakNetClientSession session, Throwable throwable) {
                logger.error(throwable.getMessage());
                logger.error(ExceptionUtils.getStackTrace(throwable));
            }

            @Override
            public void onHandlerException(InetSocketAddress address, Throwable throwable) {
                logger.error(throwable.getMessage());
                logger.error(ExceptionUtils.getStackTrace(throwable));
            }

            @Override
            public void handleUnknownMessage(RakNetClientSession session, RakNetPacket packet, int channel) {
                logger.info("Received handleUnknownMessage");
            }

            @Override
            public void handleMessage(RakNetClientSession peer, RakNetPacket packet, int channel) {
                try {
                    byte code = packet.readByte();
                    switch (code) {
                        case 20: {
                            int playerid = packet.readInt();
                            Player.register(playerid, peer);
                            Packet destPacket = new Packet();
                            destPacket.writeByte((byte) 135);
                            destPacket.writeInt(0);
                            peer.sendMessage(Reliability.RELIABLE_ORDERED, destPacket);
                            logger.info("New connection player with id: " + playerid);
                            break;
                        }
                        case 21: {
                            Player player = Player.get(peer);
                            if (player == null) {
                                logger.warn("Player not found on sending voice data");
                                break;
                            }
                            List<ImdbPlayerLocation> locationList = imdbManager.getLocationList(player.playerid, 30.0f);
                            for (ImdbPlayerLocation imdbPlayerLocation : locationList) {
                                Player.sendData(imdbManager, imdbPlayerLocation.getPlayerid(), packet);
                            }
                            break;
                        }
                        default:
                            logger.warn("Unknown code: " + code);
                    }

                } catch (InvalidChannelException ex) {
                    logger.error(ex.getMessage());
                    logger.error(ExceptionUtils.getStackTrace(ex));
                }
            }
        });

// Start server
        server.start();
    }
}

**Comment by whirvis** [comment] 2019-05-29 19:25
After a bit of digging, it seems this is an issue on my end. I'll do my best to try and fix this, I'll let you know if I need more info and when I've fixed the issue :)

**Comment by diclofoss** [comment] 2019-05-30 17:21
OK thank you. Maybe you can tell me some hotfix strategy? It's blocker for me, because voice chat requires sequence

**Comment by whirvis** [comment] 2019-05-31 21:32
@diclofoss I would suggest using v2.10.7, which does not seem to have any of these issues. v2.11.0 is extremely similar, with the main difference being some name changes and many redocs. It seems that when writing 2.11.0 I changed more code than I bargained for, and ended up causing a bunch of glitches in the process. If these issues are in v2.10.7 as well, please let me know. :)

**Comment by diclofoss** [comment] 2019-06-01 08:45
Unfortunately this issue in 2.10.7

**Comment by whirvis** [comment] 2019-06-01 17:10
That's no good. I'll get to work right away to try and resolve this issue as soon as possible.

**Comment by whirvis** [comment] 2019-06-03 00:06
@diclofoss For me, I am having no issues sending a packet with ID 0x87 (ID_GAME_MESSAGE_1) with second byte being 0x01 on reliability UNRELIABLE_SEQUENCED. I'm not sure why you're having these issues. Does the packet exceed the MTU limit? If it does, that's probably where the issues is arising.

**Comment by diclofoss** [comment] 2019-06-04 08:17
Hello!
Packet was not larger than MTU. Anyway we need to chek new version

**Comment by whirvis** [comment] 2019-06-04 13:24
Alright, let me know if this issue is fixed in the new version I sent you :)

**Closed as completed** 2019-06-06 21:52 UTC
Labels: Possible bug, v2.0
