### ISSUE TITLE
NPE when sending RELIABLE_WITH_ACK_RECEIPT with messages larger than MTU

### ISSUE THREAD

**Issue by diclofoss** [JRakNet/JRakNet#116] opened 2019-06-01 22:59 UTC
private void send(RakNetPacket packet) {
        Packet destPacket = new Packet();
        destPacket.writeByte((byte) 135);
        destPacket.writeByte((byte) 21);
        destPacket.writeInt(packet.readInt());
        int len = packet.readInt();
        destPacket.writeInt(len);
        for (int i = 0; i < len; i++) {
            destPacket.writeByte(packet.readByte());
            
        }
        peer.sendMessage(Reliability.RELIABLE_WITH_ACK_RECEIPT, destPacket);
        logger.info("Sending packet with len " + len);
    }

01:58:12 [ERROR] VoiceServer: null
01:58:12 [ERROR] VoiceServer: java.lang.NullPointerException
        at com.whirvis.jraknet.session.RakNetSession.setAckReceiptPackets(RakNetSession.java:407)
        at com.whirvis.jraknet.protocol.message.CustomPacket.encode(CustomPacket.java:96)
        at com.whirvis.jraknet.session.RakNetSession.sendCustomPacket(RakNetSession.java:457)
        at com.whirvis.jraknet.session.RakNetSession.update(RakNetSession.java:851)
        at com.whirvis.jraknet.server.RakNetServer.start(RakNetServer.java:821)
        at ru.samp_net.voiceserver.VoiceServer.main(VoiceServer.java:109)

**Comment by whirvis** [comment] 2019-06-02 02:09
Thank you for the report :)

**Comment by whirvis** [comment] 2019-06-02 21:54
This must be related to #110 and #115

**Comment by whirvis** [comment] 2019-06-03 00:26
Hi, this shows that you are on version 2.10 via the RakNetSession name. This may be fixed in version 2.11, but I am not sure. When using RELIABLE_WITH_ACK_RECEIPT and RELIABLE_ORDERED_WITH_ACK_RECEIPT in the split packet test (after fixing #110) I did not encounter this issue.

**Comment by whirvis** [comment] 2019-06-03 01:06
Hello! I have just made a commit that fixes many known issues. If you could, please use version 2.11.2 and let me know if you still have all of these issues that I have marked as "Possible bug". I believe many of these issues were caused by other issues that both of us found, however I am not entirely sure. v2.11.2 has not been built by Jenkins and has therefore not been uploaded to CodeMC. I have built this version myself manually, please use this [JAR file found inside this ZIP](https://github.com/JRakNet/JRakNet/files/3245468/JRakNet.v2.11.2.zip) instead of the maven dependencies.

**Comment by Whirvis** [comment] 2019-06-03 15:51
@diclofloss

**Comment by whirvis** [comment] 2019-06-03 15:51
@diclofoss ping

**Comment by whirvis** [comment] 2019-06-06 21:52
I'm going to go ahead and close these issues since they seem to be fixed. If any of them pop back up again for you, feel free to open another issue with the same name/content/etc.

**Closed as completed by whirvis** 2019-06-06 21:52 UTC
Labels: Possible bug, v2.0
